dimension_limits: [-450, 300, 50, 600]
velocity_limits:  [0, -20.0, 10, 20.0]
Limits: [-500, 1500]
boid_count: 50
move_to_middle_strength: 0.01
alert_distance: 100
formation_flying_distance: 10000
formation_flying_strength: 0.125
